# Site
name: Fat Garage
description: 去中心化创投社区
logo: assets/images/logo.png
favicon: assets/images/favicon.ico
baseurl:
disqus: fatgarage
email: contact@fat-garage.com
mailchimp-list: 'https://fat-garage.us4.list-manage.com/subscribe/post?u=545e6116a1da22ca6dd2b1c53&amp;id=9b2f10493c'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed

# Defaults
defaults:

  # all posts
  - scope:
      path: _posts
    values:
      layout: post
      comments: true
      author: preangel
      avatar: /assets/ventures/preangel/logo/preangel-icon.png

  # all pages
  - scope:
      path: _pages
    values:
      layout: page
  - scope:
      path: _peoples
    values:
      layout: people
      comments: true
  - scope:
      path: _portfolios
    values:
      layout: portfolio
      comments: true
  - scope:
      path: _ventures
    values:
      layout: venture
      comments: true
  - scope:
      path: _agencies
    values:
      layout: venture
      comments: true

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 30
paginate_path: /news/page:num/

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]

collections:
  lps:
    output: true
    permalink: /:collection/:path/
  peoples:
    output: true
    permalink: /:collection/:path/
  portfolios:
    output: true
    permalink: /:collection/:path/
  ventures:
    output: true
    permalink: /:collection/:path/
  agencies:
    output: true
    permalink: /:collection/:path/
